# 版本越高，支持的命令越多
# https://docs.docker.com/compose/compose-file/
version: "3"
services:
  php:
      build: ./docker-build/php
      ports:
        - "9002:9000"
        - "8017:80"
      links:
        - "postgres"
      volumes:
        - ./public:/var/www/html

  postgres:
      build: ./docker-build/postgresql
      ports:
        - "5433:5432"
      volumes:
        - ./docker-build/postgresql/data:/var/lib/postgresql
      environment:
        POSTGRES_PASSWORD: ${DOCKER_MYSQL_PASSPORD-123456}
